### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by KaiDevrim**

### CODE REVIEW

**Comment by KaiDevrim** [comment]
plz

**Comment by KaiDevrim** [comment]
wait this also goes to the discord

**Comment by KaiDevrim** [comment]
so i can spam is what im hearing

**Comment by KaiDevrim** [comment]
hey soham

**Comment by KaiDevrim** [comment]
you wouldnt believe this

**Comment by KaiDevrim** [comment]
but if you press the magical

**Comment by KaiDevrim** [comment]
looks good to me button

**Comment by KaiDevrim** [comment]
the bot will suddenly start working

**Comment by KaiDevrim** [comment]
also world hunger may be solved

**Comment by KaiDevrim** [comment]
im not too sure as it hasnt happened yet

**Comment by KaiDevrim** [comment]
im not too sure as it hasnt happened yet

**Comment by KaiDevrim** [comment]
but it is worth a shot, hopefully if this does get, looks good to me'd, then people will be happy again

**Comment by KaiDevrim** [comment]
@sohamb117

**Comment by KaiDevrim** [comment]
Imagine being head of a gosh dang TREE

**Comment by KaiDevrim** [comment]
hehe, head of LOG

**Review by sohamb117 — APPROVED** [review]

**Pull request merged**
